### ISSUE TITLE
Requirement is pinned for beewi-smartclim 0.0.7: btlewrap==0.0.2

### ISSUE THREAD

**Issue by MartinHjelmare** [alemuro/beewi_smartclim#1]
- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

**Comment by alemuro** [comment]
Thanks @MartinHjelmare , it should be fixed now :)

**Comment by MartinHjelmare** [comment]
Great! Thanks!

If you have time, please update the requirement version of the beewi_smartclim integration in home assistant.
